imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locale: ca
    main_brand_title: "espai kowo"

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        google_analytics_enabled: %google_analytics_enabled%
        google_analytics_account: "%google_analytics_account%"
        main_brand_title:         "%main_brand_title%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    java:           "%path_java%"
    node:           "%path_node%"
    filters:
        cssrewrite: ~
        less:
            node:       "%path_node%"
            node_paths: [ "%path_node_modules%" ]
    assets:
        mycss:
            inputs:
                - "@AppBundle/Resources/public/css/frontend.less"
        myjs:
            inputs:
                - "%kernel.root_dir%/../vendor/components/jquery/jquery.js"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Sonata
sonata_block:
    default_contexts: [ cms ]
    blocks:
        sonata.admin.block.admin_list:  ~

sonata_user:
    security_acl: true
    manager_type: orm


# Stof Doctrine Extensions
stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            softdeleteable: true
            timestampable:  true
            sluggable:      true
            translatable:   false
            sortable:       false
            tree:           false

# FOS User
fos_user:
    db_driver:      orm
    firewall_name:  admin
    user_class:     AppBundle\Entity\User
    group:
        group_class:   AppBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager


