imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: media.yml }

# Symfony
framework:
    translator:      { fallbacks: [ "%locale%" ] }
    secret:          "%secret%"
    router:
        resource:            "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: [ "twig" ]
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name:        EKSESSID
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - "bootstrap_3_layout.html.twig"
        - "SonataCoreBundle:Form:datepicker.html.twig"
    globals:
        google_analytics_enabled: "%google_analytics_enabled%"
        google_analytics_account: "%google_analytics_account%"
        facebook_pixel_enabled:   "%facebook_pixel_enabled%"
        facebook_pixel_id:        "%facebook_pixel_id%"
        main_brand_title:         "%project_web_title%"
        admin_tag_version:        "v1.0.59"

# Assetic
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    java:           "%path_java%"
    node:           "%path_node%"
    bundles:        [ AppBundle ]
    filters:
        cssrewrite: ~
        less:
            node:       "%path_node%"
            node_paths: [ "%path_node_modules%" ]
    assets:
        mycss:
            inputs:
                - "@AppBundle/Resources/public/css/frontend.less"
        myjs:
            inputs:
                - "%kernel.root_dir%/../vendor/components/jquery/jquery.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.js"

# Doctrine
doctrine:
    dbal:
        driver:         "pdo_mysql"
        host:           "%database_host%"
        port:           "%database_port%"
        dbname:         "%database_name%"
        user:           "%database_user%"
        password:       "%database_password%"
        charset:        "UTF8"
        server_version: "%database_server_version%"
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy:             doctrine.orm.naming_strategy.underscore
        auto_mapping:                true
        dql:
            datetime_functions:
                month: DoctrineExtensions\Query\Mysql\Month
                day:   DoctrineExtensions\Query\Mysql\Day

doctrine_migrations:
    dir_name:  "%kernel.root_dir%/../src/AppBundle/DoctrineMigrations"
    namespace: AppBundle\DoctrineMigrations

# Swiftmailer
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Sonata Block
sonata_block:
    default_contexts: [ cms ]
    blocks:
        sonata.admin.block.admin_list:  ~
        sonata.user.block.menu:         ~
        sonata.block.service.text:      ~

# Sonata User
sonata_user:
    security_acl: true
    manager_type: orm

# Stof Doctrine Extensions
stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            softdeleteable: true
            timestampable:  true
            sluggable:      true
            translatable:   false
            sortable:       false
            tree:           false

# FOS User
fos_user:
    db_driver:      orm
    firewall_name:  admin
    user_class:     AppBundle\Entity\User
    group:
        group_class:   AppBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager

# Admin
sonata_admin:
    title:      "%project_web_title%"
    title_logo: "/bundles/app/img/logo-espai-kowo-backend.png"
    options:
        html5_validate: true
        confirm_exit:   true
        use_select2:    true
        pager_links:    10
    persist_filters: true
    security:
        handler: sonata.admin.security.handler.role
    templates:
        layout: "::Admin/layout.html.twig"
        edit:   "::Admin/edit.html.twig"
        show:   "::Admin/show.html.twig"
    dashboard:
        groups:
            Blog:
                icon: "<i class='fa fa-chrome'></i>"
            Coworkers:
                icon: "<i class='fa fa-users'></i>"
            Activitats:
                icon: "<i class='fa fa-calendar-times-o'></i>"
            Contactes:
                icon: "<i class='fa fa-envelope'></i>"
            Usuaris:
                icon: "<i class='fa fa-user'></i>"
        blocks:
            -
                position: top
                type: sonata.block.service.text
                class: col-md-12
                settings:
                    content: >
                        <h1 style="margin-top:0">Content Management System</h1>
            -
                position: top
                type: sonata.admin.block.admin_list
                class: col-md-6
                settings:
                    groups: [ Blog ]
            -
                position: top
                type: sonata.admin.block.admin_list
                class: col-md-6
                settings:
                    groups: [ Coworkers ]
            -
                position: top
                type: sonata.admin.block.admin_list
                class: col-md-6
                settings:
                    groups: [ Activitats ]
            -
                position: top
                type: sonata.admin.block.admin_list
                class: col-md-6
                settings:
                    groups: [ Contactes ]
            -
                position: top
                type: sonata.admin.block.admin_list
                class: col-md-6
                settings:
                    groups: [ Usuaris ]

# CKEditor
ivory_ck_editor:
    inline: false
    configs:
        my_config:
            toolbar: standard

# EWZ Google Recaptcha
ewz_recaptcha:
    public_key:  "%recaptcha_public_key%"
    private_key: "%recaptcha_private_key%"
    locale_key:  "%locale%"

# KNP Paginator
knp_paginator:
    page_range: 5
    default_options:
        page_name: pagina
    template:
        pagination: "::Pagination/custom_pagination.html.twig"

# KNP Disqus
knp_disqus:
    api_key: "%knp_disqus.api_key%"
    forums:
        blog:
            shortname: "%knp_disqus.blog.shortname%"
