services:
    app.province_repository:
        class: AppBundle\Repository\ProvinceRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Province
    app.city_repository:
        class: AppBundle\Repository\CityRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:City
    app.category_repository:
        class: AppBundle\Repository\CategoryRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Category
    app.customer_repository:
        class: AppBundle\Repository\CustomerRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Customer
    app.invoice_repository:
        class: AppBundle\Repository\InvoiceRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Invoice
    app.provider_repository:
        class: AppBundle\Repository\ProviderRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Provider
    app.spending_repository:
        class: AppBundle\Repository\SpendingRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Spending
    app.spending_category_repository:
        class: AppBundle\Repository\SpendingCategoryRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:SpendingCategory
    app.coworker_repository:
        class: AppBundle\Repository\CoworkerRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Coworker
    app.contact_message_repository:
        class: AppBundle\Repository\ContactMessageRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:ContactMessage
    app.repositories_manager:
        class: AppBundle\Manager\RepositoriesManager
        arguments:
            - "@app.category_repository"
            - "@app.province_repository"
            - "@app.city_repository"
            - "@app.customer_repository"
            - "@app.provider_repository"
            - "@app.spending_category_repository"
