app_frontend:
    resource: "@AppBundle/Controller/Front"
    type:     annotation

sonata:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix:   /admin

_sonata_admin:
    resource: .
    type:     sonata_admin
    prefix:   /admin

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix:   /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix:   /admin/resetting

app_backend:
    resource: "@AppBundle/Controller/Admin"
    type:     annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

_presta_sitemap:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /sitemap

_redirecting_trailing_slashes:
    resource: "@AppBundle/Controller/RedirectingController.php"
    type:     annotation
