services:
# Sonata Admin
    admin.coworker:
        class: AppBundle\Admin\CoworkerAdmin
        arguments: [ ~ , AppBundle\Entity\Coworker, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Coworker", group: "Coworkers" }
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [ ~, AppBundle\Entity\Category, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Category", group: "Coworkers" }
