imports:
    - { resource: repositories.yml }
    - { resource: admins.yml }

services:
# Messaging
    app.courier:
        class: AppBundle\Service\CourierService
        arguments: [ "@swiftmailer.mailer" ]
    app.notification:
        class: AppBundle\Service\NotificationService
        arguments: [ "@app.courier", "@twig", "%mailer_destination%", "%mailer_url_base%" ]
# Menu
    app.frontend_menu_builder:
        class: AppBundle\Menu\FrontendMenuBuilder
        arguments: [ "@knp_menu.factory", "@security.authorization_checker", "@security.token_storage" ]
    app.frontend_top_menu:
        class: Knp\Menu\MenuItem
        factory: [ "@app.frontend_menu_builder", createTopMenu ]
        arguments: [ "@request_stack" ]
        tags:
            - { name: knp_menu.menu, alias: top }
# PDF Builders
    app.base_pdf:
        class: AppBundle\Pdf\BasePdf
        arguments:
            - "@app.smart_assets_helper"
    app.invoice_builder_pdf:
        class: AppBundle\Pdf\InvoiceBuilderPdf
        arguments:
            - "@white_october.tcpdf"
            - "@app.smart_assets_helper"
            - "@translator.default"
            - "%project_web_title%"
            - "%espai_kowo_fiscal_data%"
            - "%locale%"
# Sitemap
    app.sitemap:
        class: AppBundle\Listener\SitemapListener
        arguments: [ "@router", "@doctrine.orm.entity_manager" ]
        tags: [ { name: "presta.sitemap.listener" } ]
# Twig
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        arguments: [ "@app.coworker_repository" ]
        public: false
        tags:
            - { name: twig.extension }
    app.smart_assets_helper:
        class: AppBundle\Service\SmartAssetsHelperService
        arguments:
            - "@kernel"
            - "%mailer_url_base%"
# Mailchimp Manager
    app.mailchimp_manager:
        class: AppBundle\Manager\MailchimpManager
        arguments: [ "@app.notification", "%mailchimp_api_key%" ]
# Sonata Blocks
    admin.block.coworker_indicators:
        class: AppBundle\Admin\Block\CoworkerIndicatorsBlock
        tags:
            - { name: sonata.block }
        arguments: [ "admin.block.coworker_indicators", "@templating", "@doctrine.orm.entity_manager" ]
