services:
# Sonata Admin
    admin.coworker:
        class: AppBundle\Admin\CoworkerAdmin
        arguments: [ ~ , AppBundle\Entity\Coworker, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Coworker", group: "Coworkers" }
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [ ~, AppBundle\Entity\Category, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Category", group: "Coworkers" }
    admin.contactmessage:
        class: AppBundle\Admin\ContactMessageAdmin
        arguments: [ ~, AppBundle\Entity\ContactMessage, AppBundle:Admin\ContactMessageAdmin ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Contact Message", group: "Contacts" }
    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [ ~, AppBundle\Entity\User, ~, "@fos_user.user_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "User", group: "Users" }
# Messaging
    app.courier:
        class: AppBundle\Service\CourierService
        arguments: [ "@swiftmailer.mailer" ]
    app.notification:
        class: AppBundle\Service\NotificationService
        arguments: [ "@app.courier", "@twig", "%mailer_destination%", "%mailer_url_base%" ]
