imports:
    - { resource: repositories.yml }

services:
# Sonata Admin
    admin.coworker:
        class: AppBundle\Admin\CoworkerAdmin
        arguments: [ ~ , AppBundle\Entity\Coworker, AppBundle:Admin\CoworkerAdmin, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager", "@app.repositories_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Coworker", group: "Coworkers", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [ ~, AppBundle\Entity\Category, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager", "@app.repositories_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Categoria", group: "Coworkers", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.socialnetworkcategory:
        class: AppBundle\Admin\SocialNetworkCategoryAdmin
        arguments: [ ~, AppBundle\Entity\SocialNetworkCategory, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager", "@app.repositories_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Xarxa Social", group: "Coworkers", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.socialnetwork:
        class: AppBundle\Admin\SocialNetworkAdmin
        arguments: [ ~, AppBundle\Entity\SocialNetwork, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager", "@app.repositories_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Xarxes Socials", group: "Coworkers", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: false }
    admin.event:
        class: AppBundle\Admin\EventAdmin
        arguments: [ ~, AppBundle\Entity\Event, AppBundle:Admin\EventAdmin, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager", "@app.repositories_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Activitat", group: "Activitats", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.eventcategory:
        class: AppBundle\Admin\EventCategoryAdmin
        arguments: [ ~, AppBundle\Entity\EventCategory, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager", "@app.repositories_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Categoria", group: "Activitats", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.post:
        class: AppBundle\Admin\PostAdmin
        arguments: [ ~, AppBundle\Entity\Post, AppBundle:Admin\PostAdmin, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager", "@app.repositories_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Article", group: "Blog", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.tag:
        class: AppBundle\Admin\TagAdmin
        arguments: [ ~, AppBundle\Entity\Tag, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager", "@app.repositories_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Etiqueta", group: "Blog", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.contactmessage:
        class: AppBundle\Admin\ContactMessageAdmin
        arguments: [ ~, AppBundle\Entity\ContactMessage, AppBundle:Admin\ContactMessageAdmin, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager", "@app.repositories_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Missatge de Contacte", group: "Contactes", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [ ~, AppBundle\Entity\User, ~, "@fos_user.user_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Usuari", group: "Usuaris", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.province:
        class: AppBundle\Admin\ProvinceAdmin
        arguments: [ ~, AppBundle\Entity\Province, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager", "@app.repositories_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Província", group: "Facturació" }
    admin.city:
        class: AppBundle\Admin\CityAdmin
        arguments: [ ~, AppBundle\Entity\City, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager", "@app.repositories_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Ciutat", group: "Facturació" }
    admin.customer:
        class: AppBundle\Admin\CustomerAdmin
        arguments: [ ~, AppBundle\Entity\Customer, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager", "@app.repositories_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Clients", group: "Facturació" }

# Messaging
    app.courier:
        class: AppBundle\Service\CourierService
        arguments: [ "@swiftmailer.mailer" ]
    app.notification:
        class: AppBundle\Service\NotificationService
        arguments: [ "@app.courier", "@twig", "%mailer_destination%", "%mailer_url_base%" ]
# Menu
    app.frontend_menu_builder:
        class: AppBundle\Menu\FrontendMenuBuilder
        arguments: [ "@knp_menu.factory", "@security.authorization_checker", "@security.token_storage" ]
    app.frontend_top_menu:
        class: Knp\Menu\MenuItem
        factory: [ "@app.frontend_menu_builder", createTopMenu ]
        arguments: [ "@request_stack" ]
        tags:
            - { name: knp_menu.menu, alias: top }
# Sitemap
    app.sitemap:
        class: AppBundle\Listener\SitemapListener
        arguments: [ "@router", "@doctrine.orm.entity_manager" ]
        tags: [ { name: "presta.sitemap.listener" } ]
# Twig
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
# Mailchimp Manager
    app.mailchimp_manager:
        class: AppBundle\Manager\MailchimpManager
        arguments: [ "@app.notification", "%mailchimp_api_key%" ]

# Sonata Blocks
    admin.block.coworker_indicators:
        class: AppBundle\Admin\Block\CoworkerIndicatorsBlock
        tags:
            - { name: sonata.block }
        arguments: [ "admin.block.coworker_indicators", "@templating", "@doctrine.orm.entity_manager" ]
