# Sonata Block
sonata_block:
    default_contexts: [ cms ]
    blocks:
        sonata.admin.block.admin_list:   ~
        sonata.user.block.menu:          ~
        sonata.block.service.text:       ~
        admin.block.coworker_indicators: ~

# Sonata User
sonata_user:
    security_acl: true
    manager_type: orm

# Admin
sonata_admin:
    title:      "%project_web_title%"
    title_logo: "/bundles/app/img/logo-espai-kowo-backend.png"
    options:
        html5_validate: true
        confirm_exit:   true
        use_select2:    true
        pager_links:    10
    persist_filters: true
    security:
        handler: sonata.admin.security.handler.role
    templates:
        layout: "::Admin/layout.html.twig"
        list:   "::Admin/list.html.twig"
        edit:   "::Admin/edit.html.twig"
        show:   "::Admin/show.html.twig"
        batch:  "::Admin/batch.html.twig"
    dashboard:
        groups:
            Coworkers:
                icon: "<i class='fa fa-users'></i>"
            Vendes:
                icon: "<i class='fa fa-eur'></i>"
            Compres:
                icon: "<i class='fa fa-eur'></i>"
            Blog:
                icon: "<i class='fa fa-chrome'></i>"
            Activitats:
                icon: "<i class='fa fa-calendar-times-o'></i>"
            Contactes:
                icon: "<i class='fa fa-envelope'></i>"
            Configuracions:
                icon: "<i class='fa fa-cogs'></i>"
        blocks:
            -
                position: top
                type: sonata.block.service.text
                class: col-md-12
                settings:
                    content: >
                        <h1 style="margin-top:0">ERP</h1>
            -
                position: top
                type: admin.block.coworker_indicators
                class: col-md-12
