#!/bin/bash

if [ -x "$(command -v php-cs-fixer)" ]; then
    for x in "$(git diff --name-only)"; do
       php-cs-fixer fix "$x" --rules=@Symfony
    done
    for y in "$(git diff --name-only --staged)"; do
       php-cs-fixer fix "$y" --rules=@Symfony
    done
else
    echo "Unable to find php-cs-fixer command. Please, check https://github.com/FriendsOfPHP/PHP-CS-Fixer to install it globally (manual) in your system."
fi
