version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: config/nginx.dockerfile
    volumes:
      - ../../:/var/www/symfony/
    ports:
      - '8001:80'
    networks:
      - symfony

networks:
  symfony:


#     volumes:
#       - ./:/var/www/html
# #      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
#     depends_on:
#       - php
# #      - mysql
#   php:
#     build:
#       context: .
#       dockerfile: config/php.dockerfile
#    volumes:
#      - ./src:/var/www/html:delegated
#  mysql:
#    image: mysql:5.7
#    ports:
#      - 3307:3306
#    volumes:
#      - mysql:/var/lib/mysql
#    env_file:
#      - ./env/mysql.env
